apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cloud-builder
  name: cloud-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-builder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloud-builder
    spec:
      # docker-socket-volume bind mount required to build docker images
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
      containers:
      - image: gcr.io/gcp-pso-bfg-playground/github.com/joeyslalom/cloud-builder:6555389d7eb5a8a33107bcb19b188fd6d3306111
        name: cloud-builder
        resources: {}
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
status: {}
