apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: phpmyadmin
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: gcr.io/gcp-pso-bfg-playground/phpmyadmin
          name: phpmyadmin
          resources: {}
          env:
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: host
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: pass
status: {}
---

